'use client'
import Link from 'next/link'
import { useEffect, useState, useRef } from 'react'
import { useRouter } from 'next/navigation'
import { isLoggedIn } from '@/lib/eso-auth'

const TERMINAL_LINES = [
  { delay: 0,    text: '$ xcloak scan --target api.company.com',           color: '#00ffaa' },
  { delay: 800,  text: '  [AI] Planning: nmap → nuclei → nikto',            color: '#64748b' },
  { delay: 1600, text: '  [✓] Port 443: TLSv1.2 · nginx 1.24',             color: '#00aaff' },
  { delay: 2400, text: '  [!] CVE-2024-1234 · CVSS 9.1 · CRITICAL',        color: '#ff3a5c' },
  { delay: 3200, text: '  [AI] Proposing: sqlmap -u api.company.com/login', color: '#64748b' },
  { delay: 4000, text: '  [✓] SQL Injection confirmed · Report generated',   color: '#00ffaa' },
]

const FEATURES = [
  { icon: '🤖', title: 'AI Orchestration',      desc: 'Describe your target in plain English. AI plans the attack chain, picks the right tools, and adapts based on what it finds.',          color: '#00ffaa' },
  { icon: '🐳', title: '7 Docker Tools',         desc: 'nmap, nuclei, sqlmap, nikto, gobuster, ffuf, whatweb — all containerized, isolated, and orchestrated automatically.',                  color: '#00aaff' },
  { icon: '🔗', title: 'CVE Correlation',        desc: 'Every finding is cross-referenced against the live CVE database. Get CVSS scores, attack vectors, and patches instantly.',             color: '#a78bfa' },
  { icon: '📄', title: 'PDF Reports',            desc: 'Professional pentest reports generated by AI. Compliance-mapped for SOC2, ISO27001, and PCI-DSS. Ready to share.',                    color: '#00ffaa' },
  { icon: '🔄', title: 'Real-time Feedback Loop',desc: 'AI validates findings after each tool, removes false positives, and proposes follow-up tasks before you even ask.',                   color: '#00aaff' },
  { icon: '🏆', title: 'Community Hub',          desc: 'CVE tracker, exploit database, CTF challenges, learning paths, and leaderboard. Learn while you test.',                               color: '#a78bfa' },
]

const STATS = [
  { value: '7',    label: 'Security tools',  color: '#00ffaa' },
  { value: '∞',   label: 'CVEs tracked',    color: '#00aaff' },
  { value: 'AI',  label: 'Driven analysis', color: '#a78bfa' },
  { value: '₹999',label: 'Pro plan / mo',   color: '#00ffaa' },
]

function TerminalHero() {
  const [visibleLines, setVisibleLines] = useState<number[]>([])
  useEffect(() => {
    TERMINAL_LINES.forEach((line, i) => {
      setTimeout(() => setVisibleLines(prev => [...prev, i]), line.delay)
    })
  }, [])
  return (
    <div className="glass p-5 rounded-xl font-mono text-[12px] leading-6 min-h-[180px]"
      style={{ border: '1px solid rgba(0,255,170,0.12)', background: 'rgba(0,8,16,0.8)' }}>
      <div className="flex items-center gap-2 mb-3">
        <div className="w-3 h-3 rounded-full" style={{ background: '#ff5f56' }} />
        <div className="w-3 h-3 rounded-full" style={{ background: '#ffbd2e' }} />
        <div className="w-3 h-3 rounded-full" style={{ background: '#27c93f' }} />
        <span className="text-slate-700 ml-2 text-[10px]">xcloak terminal</span>
      </div>
      {TERMINAL_LINES.map((line, i) => (
        <div key={i} className="transition-all duration-300"
          style={{ color: line.color, opacity: visibleLines.includes(i) ? 1 : 0 }}>
          {line.text}
        </div>
      ))}
      {visibleLines.length === TERMINAL_LINES.length && (
        <div className="mt-1" style={{ color: '#00ffaa' }}>█<span className="animate-pulse">_</span></div>
      )}
    </div>
  )
}

export default function LandingPage() {
  const router = useRouter()
  const [countdown, setCountdown] = useState<number | null>(null)
  // Use ref to hold interval so we never call router inside setState
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const countRef    = useRef<number>(5)

  useEffect(() => {
    if (!isLoggedIn()) return
    countRef.current = 5
    setCountdown(5)
    intervalRef.current = setInterval(() => {
      countRef.current -= 1
      if (countRef.current <= 0) {
        if (intervalRef.current) clearInterval(intervalRef.current)
        // Navigate outside of setState — use setTimeout to defer past render
        setTimeout(() => router.replace('/dashboard'), 0)
      } else {
        setCountdown(countRef.current)
      }
    }, 1000)
    return () => { if (intervalRef.current) clearInterval(intervalRef.current) }
  }, [router])

  return (
    <div style={{ background: '#03050a', minHeight: '100vh' }}>
      {countdown !== null && countdown > 0 && (
        <div className="fixed top-0 left-0 right-0 z-[100] flex items-center justify-between px-5 py-2.5"
          style={{ background: 'rgba(0,255,170,0.08)', borderBottom: '1px solid rgba(0,255,170,0.2)' }}>
          <span className="font-mono text-[11px] text-slate-400">
            Already logged in. Redirecting in{' '}
            <span className="text-accent font-bold">{countdown}s</span>…
          </span>
          <button onClick={() => { if (intervalRef.current) clearInterval(intervalRef.current); router.replace('/dashboard') }}
            className="font-mono text-[11px] font-bold px-3 py-1 rounded-lg cursor-pointer transition-all hover:opacity-80"
            style={{ background: 'rgba(0,255,170,0.15)', border: '1px solid rgba(0,255,170,0.3)', color: '#00ffaa' }}>
            Go now →
          </button>
        </div>
      )}

      <nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-5 py-3"
        style={{ background: 'rgba(3,5,10,0.9)', backdropFilter: 'blur(20px)', borderBottom: '1px solid rgba(255,255,255,0.05)' }}>
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg flex items-center justify-center text-base"
            style={{ background: 'linear-gradient(135deg,#00ffaa22,#00aaff22)', border: '1px solid rgba(0,255,170,0.2)' }}>🛡</div>
          <span className="text-lg font-black">X<span style={{ color: '#00ffaa' }}>cloak</span></span>
        </div>
        <div className="hidden sm:flex items-center gap-5">
          <Link href="/pricing"   className="font-mono text-[12px] text-slate-500 hover:text-slate-200 transition-colors">Pricing</Link>
          <Link href="/dashboard" className="font-mono text-[12px] text-slate-500 hover:text-slate-200 transition-colors">Dashboard</Link>
          <Link href="/cve"       className="font-mono text-[12px] text-slate-500 hover:text-slate-200 transition-colors">CVE Tracker</Link>
        </div>
        <div className="flex items-center gap-2">
          <Link href="/login"    className="font-mono text-[12px] px-3 py-1.5 rounded-lg transition-all hover:text-white" style={{ color: '#64748b' }}>Sign in</Link>
          <Link href="/register" className="font-mono text-[12px] font-bold px-4 py-1.5 rounded-lg transition-all hover:opacity-80"
            style={{ background: 'rgba(0,255,170,0.1)', border: '1px solid rgba(0,255,170,0.3)', color: '#00ffaa' }}>Start free</Link>
        </div>
      </nav>

      <section className="pt-28 pb-20 px-5">
        <div className="max-w-5xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full mb-6 font-mono text-[10px] font-bold"
                style={{ background: 'rgba(0,255,170,0.08)', border: '1px solid rgba(0,255,170,0.2)', color: '#00ffaa' }}>
                <span className="live-dot" /> AI-Powered Penetration Testing
              </div>
              <h1 className="text-4xl sm:text-5xl font-black leading-tight mb-6">
                Security testing<br /><span style={{ color: '#00ffaa' }}>that thinks</span><br />for itself
              </h1>
              <p className="font-mono text-[13px] text-slate-500 leading-7 mb-8 max-w-md">
                Describe your target in plain English. XCloak's AI plans the attack, orchestrates 7 Docker security tools in parallel, validates findings, and generates a professional PDF report — automatically.
              </p>
              <div className="flex flex-wrap gap-3">
                <Link href="/register" className="font-mono text-[13px] font-bold px-6 py-3 rounded-xl transition-all hover:opacity-80"
                  style={{ background: 'rgba(0,255,170,0.12)', border: '1px solid rgba(0,255,170,0.35)', color: '#00ffaa' }}>
                  Start free — no card needed
                </Link>
                <Link href="/pricing"  className="font-mono text-[13px] font-bold px-6 py-3 rounded-xl transition-all hover:opacity-80"
                  style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', color: '#94a3b8' }}>
                  See pricing →
                </Link>
              </div>
              <p className="font-mono text-[10px] text-slate-700 mt-4">3 free scans/day · No credit card · Instant setup</p>
            </div>
            <div><TerminalHero /></div>
          </div>
        </div>
      </section>

      <section className="py-10 px-5" style={{ borderTop: '1px solid rgba(255,255,255,0.04)', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
        <div className="max-w-4xl mx-auto grid grid-cols-2 sm:grid-cols-4 gap-6">
          {STATS.map(s => (
            <div key={s.label} className="text-center">
              <div className="text-3xl font-black mb-1" style={{ color: s.color }}>{s.value}</div>
              <div className="font-mono text-[10px] text-slate-600 uppercase tracking-widest">{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      <section className="py-20 px-5">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-2xl sm:text-3xl font-black mb-3">Everything a security team needs</h2>
            <p className="font-mono text-[12px] text-slate-600 max-w-md mx-auto">
              From recon to report, all in one platform — at a price that doesn't require board approval.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {FEATURES.map(f => (
              <div key={f.title} className="glass p-5 rounded-xl">
                <div className="text-2xl mb-3">{f.icon}</div>
                <div className="font-bold text-[14px] mb-2" style={{ color: f.color }}>{f.title}</div>
                <div className="font-mono text-[11px] text-slate-600 leading-5">{f.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 px-5" style={{ background: 'rgba(0,255,170,0.015)' }}>
        <div className="max-w-4xl mx-auto">
          <h2 className="text-2xl font-black text-center mb-14">How it works</h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
            {[
              { step:'01', title:'Describe the target', desc:'Type your goal in plain English. No config needed.', color:'#00ffaa' },
              { step:'02', title:'AI builds the plan',  desc:'Claude orchestrates nmap, nuclei, nikto and more in parallel.', color:'#00aaff' },
              { step:'03', title:'Get the report',      desc:'A professional PDF with findings, CVE IDs, CVSS scores, and remediation.', color:'#a78bfa' },
            ].map(step => (
              <div key={step.step} className="glass p-5 rounded-xl">
                <div className="font-mono text-[32px] font-black mb-3 opacity-20" style={{ color: step.color }}>{step.step}</div>
                <div className="font-bold text-[14px] mb-2" style={{ color: step.color }}>{step.title}</div>
                <div className="font-mono text-[11px] text-slate-600 leading-5">{step.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 px-5">
        <div className="max-w-2xl mx-auto text-center">
          <h2 className="text-2xl font-black mb-3">Start free. Scale when ready.</h2>
          <p className="font-mono text-[12px] text-slate-600 mb-8">
            Free tier gives you 3 real scans per day, forever. Pro unlocks AI analysis, PDF reports, and all tools for ₹999/month.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link href="/register" className="font-mono text-[13px] font-bold px-8 py-3 rounded-xl transition-all hover:opacity-80"
              style={{ background: 'rgba(0,255,170,0.1)', border: '1px solid rgba(0,255,170,0.35)', color: '#00ffaa' }}>
              Start for free
            </Link>
            <Link href="/pricing"  className="font-mono text-[13px] font-bold px-8 py-3 rounded-xl transition-all hover:opacity-80"
              style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)', color: '#94a3b8' }}>
              View all plans
            </Link>
          </div>
        </div>
      </section>

      <footer className="py-8 px-5 text-center" style={{ borderTop: '1px solid rgba(255,255,255,0.04)' }}>
        <div className="font-mono text-[10px] text-slate-700 space-y-2">
          <div>XCloak · AI-Powered Security Platform · <a href="mailto:admin@xcloak.tech" className="text-accent hover:underline">admin@xcloak.tech</a></div>
          <div className="flex flex-wrap justify-center gap-x-4 gap-y-1">
            <Link href="/pricing"  className="hover:text-slate-400 transition-colors">Pricing</Link>
            <Link href="/login"    className="hover:text-slate-400 transition-colors">Login</Link>
            <Link href="/register" className="hover:text-slate-400 transition-colors">Register</Link>
            <Link href="/terms"    className="hover:text-slate-400 transition-colors">Terms</Link>
            <Link href="/privacy"  className="hover:text-slate-400 transition-colors">Privacy</Link>
          </div>
          <div className="text-slate-800">© {new Date().getFullYear()} XCloak. All rights reserved.</div>
        </div>
      </footer>
    </div>
  )
}
